### ISSUE TITLE
Local PDF is null when sharing

### ISSUE THREAD

**Issue by brandlee** [GRizzi91/bouquet#10]
when I use share, the `shareFile(verticalPdfReaderState.file)`always get null

**Comment by brandlee** [comment]
I find the problem:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/11416751/222951695-f3456ca4-5a26-4140-b719-50bb564d2239.png">
when ResourceType is Local, u didn't set file value

**Comment by GRizzi91** [comment]
Fixed in 1.0.1
