### ISSUE TITLE
Accessibility support

### ISSUE THREAD

**Issue by JBayangosB** [GRizzi91/bouquet#13]
This library is fantastic for my needs but unfortunately its not quite accessible right now in its current state. 

Using talkback with the PDF reader leads to a whole bunch of "Unlabelled" announcements by the accessibility service and a best guess at what the content contains. 

Ideally we are able to simply strip text from each bitmap and provide it as part of the `ContentDescription` when rendering in compose.

I may explore ways to resolve this 🙂

**Comment by GRizzi91** [comment]
I honestly don't know if it can be a good approach, the text of a page can be very long and could congest the talkback. However feel free to open a PR if you find a valid way.

**Comment by JBayangosB** [comment]
Opened PR: https://github.com/GRizzi91/bouquet/pull/14
