### ISSUE TITLE
Allow headers for remote resource

### ISSUE THREAD

**Issue by benedict-lim** [GRizzi91/bouquet#16]
Thanks for the library! It is especially helpful because there is no official framework that displays PDF easily. (at least to my knowledge)

I am trying to load remote resource from cloud storage such as AWS, thus I need to set some request headers.
It would be great if I could set the headers when declaring `ResourceType.Remote`.

Hope you would give it a consideration!

**Comment by GRizzi91** [comment]
I added the headers support in 1.0.2, you can add an hashmap with headers in ResourceType.Remote. The version is already released
