### ISSUE TITLE
When PDF file is about 50 MB it doesn't work

### ISSUE THREAD

**Issue by 10zgurr** [GRizzi91/bouquet#26]
Hi, 

thank you for the library first of all. I have this issue that when I try with a 50 MB file's URL (https://www.learningcontainer.com/sample-pdf-files-for-testing) it doesn't work :/

**Comment by ncubes-dev** [comment]
I also this problem byt overally the library is awesome

**Comment by GRizzi91** [comment]
This url (https://www.learningcontainer.com/sample-pdf-files-for-testing) is not a pdf resource so it's normal that you cant open the pdf. All in all can you share your code? If you prefer you can upload your project on a private repo and add me has a contributor @10zgurr

**Comment by 10zgurr** [comment]
```
val pdfState = rememberVerticalPdfReaderState(
        resource = ResourceType.Remote("https://myreport.altervista.org/sample-50-MB-pdf-file.pdf"),
        isZoomEnable = true
    )
    Box {
        VerticalPDFReader(
            state = pdfState,
            modifier = Modifier
                .fillMaxSize()
                .background(color = Color.Gray)
        )
        pdfState.file?.let { file ->
            Button(
                modifier = Modifier.size(60.dp),
                onClick = {
                    // save file
                    share(context = context, pdfFile = file)
                }
            ) {
                Icon(
                    modifier = Modifier.size(60.dp),
                    painter = painterResource(id = android.R.drawable.ic_menu_share),
                    contentDescription = "share"
                )
            }
        }
    }
```

**Comment by 10zgurr** [comment]
this is the code blocks that im using with `implementation 'io.github.grizzi91:bouquet:1.0.2'` lib version

**Comment by 10zgurr** [comment]
it stucks in this screen forever even though I believe the download is finished :/ there is no log in the logcat and I'm testing on pixel5 device android 11 (same issue for android emulator with android 13)

pixel5:
![Screenshot_20230511_144514](https://github.com/GRizzi91/bouquet/assets/20328524/c4229b58-5148-474f-a653-f29788393b5e)

emulator android 13:
![Screenshot_1683809346](https://github.com/GRizzi91/bouquet/assets/20328524/1c838eaa-133b-4e38-88e2-ccb9385a023a)

**Comment by ihor-bezeka** [comment]
Hello @GRizzi91, your lib looks awesome and works fine with PDF files for 2-5 pages, but with bigger files, I have a problem:
 
On some devices, I have an OutOfMemoryError. (Sony Xperia Z5 Compact)

On a virtual device, Google Pixel 2 (with default memory settings), when I try to load a huge PDF file, it looks like nothing happened, and the loading is stuck.

**Comment by GRizzi91** [comment]
@ihor-bezeka this sounds me strange, in demo app the remote file is a pdf with more thant 5 page and work well. I also tested with bigger and heavy pdf and i never get OOM. Can you let me have the pdf that you are talking abount?

**Comment by ihor-bezeka** [comment]
@GRizzi91, sorry for the late response. Here it is: https://www.thebookcollector.co.uk/sites/default/files/the-book-collector-example-2018-04.pdf

**Comment by ihor-bezeka** [comment]
The same problem with the assets pdf file (raw/lorem_ipsum.pdf). On Pixel 2 API v.23

I have tested on Samsung s10, s22, and emulators Resizable (Experimental) API v.33 everything works fine.
But on Pixel 2 API v.23, OOM throws at the start of loading, and on Pixel 2 API v.29, OOM throws near the end of the loading even if the memory settings of these emulators are the same.

Maybe setting these memory settings will help with catching the OOM:
<img width="600" alt="Screenshot 2023-05-16 at 15 26 22" src="https://github.com/GRizzi91/bouquet/assets/65342653/af7d7dd3-d483-4e6c-b5c7-e76e04630043">

**Comment by GRizzi91** [comment]
Ok i found the problem, ill fix the issue as soon as possible

**Comment by GRizzi91** [comment]
@ihor-bezeka @10zgurr 
New version is out 1.1.2, now the lib will require only 1/8 of the memory required by the 1.1.1

**Comment by ihor-bezeka** [comment]
@GRizzi91, it works much better! But now I have OOM when trying to scroll through a PDF document. 
When the document scrolled to the 3-5 page, I got OOM.

Should I open a new Issue, or can this bug be solved in the scope of this issue?

**Comment by ncubes-dev** [comment]
When I open local documents that have many pages or bigger size
