### ISSUE TITLE
Zooming doesn't always work

### ISSUE THREAD

**Issue by headsvk** [GRizzi91/bouquet#9]
Hi, thanks for the library, it works pretty well!

However, I find it hard to pinch to zoom. It only works sometimes for me, even on the emulator.
Have you considered adding double tap to zoom?

**Comment by GRizzi91** [comment]
Hi, thanks for the request. I'm developing a new bunch of features, like preview support, ill add you request in the next release but i can't give you a release date i'm sorry.

**Comment by GRizzi91** [comment]
@headsvk Hi, can you try 1.1.0-beta01 version? I switched to double tap to zoom, let me know if you like it.

**Comment by GRizzi91** [comment]
Pinch to zoom is replaced with double tap in version `1.1.1`

**Comment by libhide** [comment]
@GRizzi91 Why was pinch to zoom replaced with double tap? 🤔 Are there any plans of supporting pinch to zoom in the future?

**Comment by headsvk** [comment]
@GRizzi91 thanks for the update, I'm sorry I didn't get to try it earlier.

It works very well! Is it possible to add an animation to zooming like in Google's PDF viewer?

**Comment by romans-boi** [comment]
@GRizzi91 Hey, just wanted to bump up @libhide's question. 

Would it be possible to add something that would allow us to customise which zoom we want to use? I have a requirement for an app to have pinch to zoom, and this is the only thing that's making me hesitant to use this library, everything else looks great.
